import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC', // Cleaner, cooler gray
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: 18,
    color: '#334155',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  searchSection: {
    backgroundColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 16,
    zIndex: 10,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '500',
  },
  categoryScroll: {
    flexGrow: 0,
    paddingBottom: 8,
  },
  chip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
  },
  chipActive: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
    shadowColor: '#10B981',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  chipText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  herbsList: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  herbCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 12,
    marginBottom: 20,
    shadowColor: '#64748B',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.06,
    shadowRadius: 24,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F8FAFC',
  },
  herbImage: {
    width: 110,
    height: 110,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    marginRight: 16,
  },
  herbInfo: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 4,
  },
  herbName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  scientificName: {
    fontSize: 13,
    color: '#10B981',
    fontStyle: 'italic',
    marginBottom: 8,
    fontWeight: '600',
  },
  description: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 12,
  },
  benefitsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  benefitTag: {
    fontSize: 10,
    color: '#059669',
    fontWeight: '700',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    overflow: 'hidden',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#064E3B',
    marginTop: 20,
  },
  emptyText: {
    fontSize: 15,
    color: '#059669',
    marginTop: 8,
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 22,
  },

  /* Skeleton Styles */
  skeletonCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#ECFDF5',
    marginHorizontal: 16,
    shadowColor: '#047857',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  skeletonImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    backgroundColor: '#F0FDF4',
    marginRight: 16,
  },
  skeletonContent: {
    flex: 1,
    justifyContent: 'center',
  },
  skeletonTitle: {
    width: '70%',
    height: 20,
    borderRadius: 6,
    backgroundColor: '#F0FDF4',
    marginBottom: 10,
  },
  skeletonSubtitle: {
    width: '50%',
    height: 14,
    borderRadius: 4,
    backgroundColor: '#F0FDF4',
    marginBottom: 16,
  },
  skeletonLine: {
    width: '100%',
    height: 12,
    borderRadius: 4,
    backgroundColor: '#F0FDF4',
    marginBottom: 8,
  },
  skeletonLastLine: {
    width: '60%',
    height: 12,
    borderRadius: 4,
    backgroundColor: '#F0FDF4',
  },
});
