import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Commercial Premium Palette
export const COLORS = {
  emerald: '#059669',
  emeraldDark: '#047857',
  emeraldLight: '#10B981',
  forest: '#15803d',
  forestDark: '#14532d',
  mint: '#d1fae5',
  mintBorder: '#a7f3d0',
  slate: '#F8FAFC',
  slateBorder: '#E2E8F0',
  textMain: '#0F172A',
  textMuted: '#64748B',
  danger: '#DC2626',
  warning: '#F59E0B',
  white: '#FFFFFF',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  resultsContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
  },

  /* ── Camera View ─────────────────────────────── */
  cameraFill: {
    flex: 1,
  },

  center: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F4F6'
  },

  permBtn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#10B981',
    borderRadius: 8,
    marginTop: 20,
  },
  permBtnText: {
    color: '#fff',
    fontWeight: '600',
  },

  /* Top Overlay */
  overlayTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingBottom: 24,
    backgroundColor: 'rgba(2, 44, 34, 0.4)', // Darker indigo-tinted overlay
  },
  topBarContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 60,
  },
  overlayTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* ── Camera Guide & AI Targets ──────────────── */
  frameContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 80, // Offset for bottom controls
  },
  guideContainer: {
    width: 280,
    height: 350,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  corner: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  topLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 16,
  },
  topRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 16,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 16,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 16,
  },
  aiTargetContainer: {
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiTargetDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  aiTargetPulse: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 2,
    borderColor: 'rgba(16, 185, 129, 0.5)',
  },
  frameText: {
    marginTop: 24,
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
    letterSpacing: 0.5,
  },

  /* Bottom Controls */
  overlayBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(2, 44, 34, 0.6)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 30,
    paddingBottom: 40,
  },

  /* Upload / Tips Buttons */
  sideBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 70,
  },
  sideBtnCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  sideBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },

  /* Shutter */
  shutterOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 6,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  shutterInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    borderWidth: 4,
    borderColor: COLORS.forest,
  },

  /* ── Preview / Analysis ──────────────────────── */
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backBtn: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#111827',
  },
  scrollContent: {
    paddingBottom: 40,
  },

  /* Image Card in Preview */
  imageCard: {
    margin: 16,
    height: 300,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
    position: 'relative',
  },
  previewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageActions: {
    position: 'absolute',
    bottom: 12,
    right: 12,
  },
  retakeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  retakeText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },

  /* Analyze Section */
  analyzeSection: {
    paddingHorizontal: 24,
    alignItems: 'center',
    marginTop: 8,
  },
  instructTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  instructText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  analyzeButton: {
    width: '100%',
    backgroundColor: COLORS.emerald,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.emerald,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  analyzeDisabled: {
    backgroundColor: '#6B7280',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    opacity: 0.85,
  },
  analyzeBtnText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  /* Results Section */
  resultsSection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  resultsHeaderTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  resultCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  confidenceBadge: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  confidenceText: {
    color: COLORS.emerald,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  plantName: {
    fontSize: 22,
    fontWeight: '900',
    color: COLORS.textMain,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  scientificName: {
    fontSize: 15,
    color: COLORS.textMuted,
    fontStyle: 'italic',
    marginBottom: 16,
  },
  descText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
    marginBottom: 16,
  },
  detailsLink: {
    alignSelf: 'flex-start',
  },
  detailsLinkText: {
    color: '#10B981',
    fontWeight: '600',
    fontSize: 14,
  },

  /* Modal Sheet */
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: '80%',
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    elevation: 10,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  /* ── Scanning Overlay ──────────────────────── */
  scanningOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanningLine: {
    width: '100%',
    height: 60,
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    zIndex: 5,
    justifyContent: 'center', // Center children vertically
  },
  scanningLineCenter: {
    height: 2,
    width: '100%',
    backgroundColor: 'rgba(52, 211, 153, 0.8)',
    shadowColor: '#10B981',
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 4,
  },
  scanningBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  scanningBadgeText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.5,
  },

  /* ── Modal Redesign Styles ───────────────────── */
  modalMainHeader: {
    marginBottom: 20,
  },
  modalConfidenceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginTop: 8,
    gap: 4,
  },
  modalConfidenceText: {
    color: '#059669',
    fontSize: 12,
    fontWeight: '700',
  },

  /* Safety Card */
  safetyCard: {
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    marginBottom: 20,
  },
  safetyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  safetyTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: COLORS.danger,
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  safetyIntro: {
    fontSize: 14,
    color: '#991B1B',
    marginBottom: 16,
    lineHeight: 20,
    fontWeight: '500',
  },
  lookAlikeItem: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  lookAlikeInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  lookAlikeName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  dangerBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  dangerHigh: {
    backgroundColor: '#DC2626',
  },
  dangerMid: {
    backgroundColor: '#F59E0B',
  },
  dangerText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '800',
  },
  lookAlikeReason: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 18,
  },

  /* AI Section - Minimalist Redesign */
  aiSection: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  aiSectionHeader: {
    marginBottom: 16,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  aiBadgeText: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  aiTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -0.5,
  },
  aiInputContainer: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 4,
    marginBottom: 12,
  },
  aiInput: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40, // Space for the button
    fontSize: 15,
    color: '#1F2937',
    minHeight: 110,
    textAlignVertical: 'top',
  },
  aiInputActions: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiAskBtn: {
    backgroundColor: '#111827',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiAskBtnDisabled: {
    backgroundColor: '#E5E7EB',
  },
  aiQuickBtnContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  aiQuickBtn: {
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignSelf: 'center',
    width: '100%',
    alignItems: 'center',
  },
  aiQuickBtnText: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  aiResponseBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  aiResponseText: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 24,
  },
  aiResetBtn: {
    marginTop: 16,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  aiResetBtnText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '600',
  },

  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  closeModalBtn: {
    padding: 4,
    backgroundColor: '#F3F4F6',
    borderRadius: 50,
  },
  modalPlantName: {
    fontSize: 26,
    fontWeight: '900',
    color: COLORS.textMain,
    letterSpacing: -0.8,
    marginBottom: 4,
  },
  modalSciName: {
    fontSize: 16,
    color: COLORS.textMuted,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 16,
  },
  sectionHead: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 8,
    marginTop: 8,
  },
  sectionBody: {
    fontSize: 15,
    color: '#4B5563',
    lineHeight: 22,
    marginBottom: 16,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  tag: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  tagText: {
    color: '#4B5563',
    fontSize: 13,
    fontWeight: '500',
  },
  modalActions: {
    marginTop: 20,
  },
  actionBtnPrimary: {
    backgroundColor: '#10B981',
    paddingVertical: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#10B981',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  actionBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },

  /* ── Scan History Styles ─────────────────────── */
  clearBtn: {
    padding: 8,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#374151',
    marginTop: 16,
  },
  emptySubText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  historyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  historyThumb: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  historyInfo: {
    flex: 1,
    marginLeft: 16,
  },
  historyName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 2,
  },
  historyDate: {
    fontSize: 12,
    color: '#6B7280',
  },

  /* ── Comparison & View Toggle ────────────────── */
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
    alignSelf: 'center',
    width: '100%',
  },
  viewToggleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  viewToggleBtnActive: {
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  viewToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  viewToggleTextActive: {
    color: COLORS.emerald,
  },
  comparisonContainer: {
    flexDirection: 'row',
    height: 280,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: COLORS.slate,
    borderWidth: 1.5,
    borderColor: COLORS.slateBorder,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  compHalf: {
    flex: 1,
    position: 'relative',
  },
  compImage: {
    width: '100%',
    height: '100%',
  },
  compLabel: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  compLabelText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '700',
  },
  compDivider: {
    width: 2,
    backgroundColor: '#FFF',
    height: '100%',
  },
  illustrationContainer: {
    width: '100%',
    height: 300,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  illustrationImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  noIllustration: {
    alignItems: 'center',
    padding: 20,
  },
  noIllustrationText: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },

  /* ── Feedback Section ──────────────────────── */
  feedbackSection: {
    marginTop: 10,
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 0,
  },
  feedbackChoices: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  choiceBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    backgroundColor: '#F8FAFC',
  },
  choiceBtnActiveCorrect: {
    backgroundColor: COLORS.emerald,
    borderColor: COLORS.emerald,
  },
  choiceBtnActiveIncorrect: {
    backgroundColor: COLORS.danger,
    borderColor: COLORS.danger,
  },
  choiceText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4B5563',
  },
  choiceTextActive: {
    color: '#FFF',
  },
  correctionContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  correctionInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#1F2937',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  ratingContainer: {
    marginBottom: 20,
  },
  stars: {
    flexDirection: 'row',
    gap: 10,
  },
  submitBtn: {
    backgroundColor: '#111827',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  submitBtnDisabled: {
    opacity: 0.4,
  },
  submitBtnText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '700',
  },
  successFeedback: {
    alignItems: 'center',
    paddingVertical: 20,
    backgroundColor: '#F0FDF4',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  successFeedbackTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#111827',
    marginTop: 12,
    marginBottom: 4,
  },
  successFeedbackText: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 20,
  },
});
